# Header
logo_text: # Add text logo instead of logo image
menu:
  Home: /
  Archives: about
  Categories: about
  About: about

# Content
excerpt_link: Read More
toc: true
fancybox: true

#comments
disqus_shortname: blairos-sn

# Miscellaneous
google_analytics:
favicon: /favicon.png

